[build-system]
requires = ["scikit-build-core", "numpy"]
build-backend = "scikit_build_core.build"

[project]
name = "f77ex"
version = "0.0.1"
dependencies = ["numpy"]
license = "MIT-0 AND BSD-2-Clause AND GPL-3.0-with-GCC-exception"
license-files = ["LICENSE*.txt"]

[tool.scikit-build]
wheel.exclude = ["f77ex/src/", "f77ex/scipy-openblas-symbols"]

[tool.cibuildwheel]
# scipy-openblas32 version specified here
before-build = "python {project}/build-tools/cibw_before_build.py 0.3.31.22.1 {project}"
test-command = "python -m f77ex.test.test_mat_det"

skip = ["cp38-*", "cp39-*", "cp3??t-*", "*-win32", "*-win_arm64"]

[tool.cibuildwheel.linux]
repair-wheel-command = [
  "LD_LIBRARY_PATH=./build-libs",
  "auditwheel repair -w {dest_dir} {wheel}",
]

[tool.cibuildwheel.windows]
repair-wheel-command = [
  "pip install delvewheel",
  "delvewheel repair --add-path build-libs -w {dest_dir} {wheel}"
]

[tool.cibuildwheel.macos]
repair-wheel-command = "bash {project}/build-tools/cibw_repair_wheel_macos.sh {dest_dir} {wheel} {project}"
