Demonstrate creating a Python wheel from Fortran source linked against
https://github.com/MacPython/openblas-libs

* manylinux build

Needs bash and docker.  Tested on Debian 13 x64 host.  Includes auditwheel step.

Run ~./ci/docker-build.bash~ to build ~f77ex-0.0.1-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl~.

* cibuildwheel

** basic check

~CIBW_BUILD=cp313-manylinux_x86_64 cibuildwheel~

** Windows

 - compile with Ninja, gcc, gfortran via SKBUILD_CMAKE_ARGS
   - perhaps using ninja or make one can still use msvc - does it matter?

 - wheel repair
   - happens after build environment deleted
   - install scipy_openblas32
   - install delvewheel
   - use delvewheel_wrapper.py to manipulate PATH to find scipy_openblas DLL

** TODO install openblas library

[2026-03-08 Sun] conclusion: this doesn't work.

instead of installing scipy-openblas wheel at repair time, install the openblas library as part of the build step

test this on linux first.

For Windows and Linux, want to install everything from lib dir.  For MacOS probably only libscipy-openblas.

*** linux results

here RPATH might be RUNPATH - CMake handles that.

a82cf9b, tools/basic-build.bash

- installed the openblas libraries alongside own library
- used RPATH ~${ORIGIN}~ for own library

that builds a wheel that *doesn't* need repairing (!), but also auditwheel fails to process (!!), even with LD_LIBRARY_PATH setup.

**** auditwheel detail

I'm going to not INSTALL_RPATH etc, and also not install the extra libs, and see if I can run auditwheel manually.

That worked fine.  I wonder why the same command failed when I ran it with the wheel where I had set RPATH to ${ORIGIN}.

... hm.  I wonder if CMake's RPATH business screwed up something in delocate?

